-- AlterTable
ALTER TABLE "Hotel" ADD COLUMN "storageUsedMB" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "storageLimitMB" DOUBLE PRECISION NOT NULL DEFAULT 1024,
ADD COLUMN "apiRequestsCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "apiRequestsLimit" INTEGER NOT NULL DEFAULT 10000;
